### PR TITLE
Fix discord msg

### PR DESCRIPTION
**Pull request by qawery-just-sad**
The discord messages will now be compared to SR
tested but as @sneak-it said 2 approvals are needed and i want someone else to test it as well

### CODE REVIEW

**Comment by Kyli3Boi** [comment]
Im currently testing 006d817. Will give feedback once i have collected enough data

**Comment by Kyli3Boi** [comment]
Still seems to be the same but as you guys have pointed out before could be due to the version im using...
image

**Comment by qawery-just-sad** [comment]
strange 
image

**Comment by Kyli3Boi** [comment]
I think your testing method is incorrect.

It works perfectly fine when it's the same player that beat the record as you have already finished the map. The issue is when a different player finishes the map/bonus for the 1st time and beats the record, that's when it bugs out

**Comment by Kyli3Boi** [comment]
Just Sad and myself have tested this out and it working as intended on his server. Unsure as to why mine is not working as intended but could be a version issue or something. 

But this seems good to merge as its working as intended (at least on the version Just Sad is using)

**Comment by stunslave** [comment]
Can you make it so it shows the tier of the map next to the map name. :P

Map
surf_frost (Tier2)

**Comment by qawery-just-sad** [comment]
that wasn't a question was it?

**Comment by olokos** [comment]
Thank you for your contribution! 👍

**Pull request merged**
