### PR TITLE
Added Style commands

### PR DESCRIPTION
**Pull request by qawery-just-sad**
made mistakes
not tested
have fun

### CODE REVIEW

**Comment by qawery-just-sad** [comment]
there is an issue command sm_ff is used by sourcemod to display friendly fire any suggestions?

**Comment by qawery-just-sad** [comment]
I hope everyone aggress that !faf = fast-foward

**Comment by Kyli3Boi** [comment]
Would !ffw not be better as fw is the correct abbreviation for forward

**Comment by stunslave** [comment]
I made it !fff for the mean time. Couldn't think of anything. lol

**Comment by qawery-just-sad** [comment]
think we need a strawpool for this xD

**Comment by qawery-just-sad** [comment]
@olokos no issues on my server

**Comment by olokos** [comment]
Thank you @qawery-just-sad 
Merged!

**Pull request merged**
