### PR TITLE
add SurfTimer-telefinder

### PR DESCRIPTION
**Pull request by dPexxIAM**
https://discordapp.com/channels/366959507764674560/379572504542445568/747038099552469082

### CODE REVIEW

**Review by Bara — APPROVED** [review]

**Comment by qawery-just-sad** [comment]
is it only me or should this be in it's own repo? so like still under Surftimer organization but in it's own repo

**Comment by Bara** [comment]
same for https://github.com/surftimer/Surftimer-olokos/pull/240
but I would keep it for now. We finally should release a stable version and then we can start with this change. 🤔

**Comment by Bara** [comment]
Can't merge it. @dPexxIAM feel free to merge it with admin rights, otherwise we need to wait for another approval.

**Comment by dPexxIAM** [comment]
@Bara for some reason I can't merge my own commit without approvals, other's I can merge without review approvals, however :s

**Pull request merged**
