### PR TITLE
Overhauling part of old SQL Stuff

### PR DESCRIPTION
**Pull request by Bara**
**Attention: This changes aren't tested yet!** 😂 

- Added a few new messages
- Replaced old dbi natives with latest dbi methodmaps
  - All queries should be threaded now
- Clean up sql.sp a bit by removing some old commented stuff
- Removed sqlite completely from the code
- Fix a lot of potential memory leaks (mostly on a failed query)
- Moved some DB stuff vom OnMapStart/OnConfigsExecuted to sql.sp after successful table creations
- Updated Checkpoints create table query
- Some small changes more
- Upgrades are now optional by using a command (`sm_surftimer_upgrade` or `sm_surftimer_migrate`)
  - This release requires a database migration to be run, you may do so with `sm_surftimer_upgrade`

### CODE REVIEW

**Comment by Bara** [comment]
Should be ready for review. Table creation works fine on my test server, but nothing more was tested. Here's the latest build from this branch for testing.
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4542817/SurfTimer.zip)

**Comment by LubricantJam** [comment]
@Bara Can you bring this up to date with the dev branch and I'll run some tests, seeing as no one else is right now.

**Comment by Bara** [comment]
It's updated -> https://github.com/olokos/Surftimer-olokos/pull/71/commits/b8f888bb037d0a62591d17a7ec1d9c5d6d61b4ea

**Comment by Bara** [comment]
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4589916/SurfTimer.zip)
for everyone who wants to test this.

**Comment by olokos** [comment]
I reported current issues in #97

**Comment by Bara** [comment]
Most recent version for testing.
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4600951/SurfTimer.zip)

**Comment by Bara** [comment]
Latest version: 
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4605926/SurfTimer.zip)

**Comment by Bara** [comment]
With latest dev changes:
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4611030/SurfTimer.zip)

**Comment by olokos** [comment]
@Bara 
I reported multiple times this issue on discord, mentioning you there each time :(
`L 05/11/2020 - 19:30:55: [SM] Exception reported: Array index out-of-bounds (index 66, limit 66)
L 05/11/2020 - 19:30:55: [SM] Blaming: SurfTimer.smx
L 05/11/2020 - 19:30:55: [SM] Call stack trace:
L 05/11/2020 - 19:30:55: [SM]   [1] Line 607, d:\Cloud\SourcePawn\GitHub\Surftimer-olokos\addons\sourcemod\scripting\surftimer/sql.sp::CalculatePlayerRank
L 05/11/2020 - 19:30:55: [SM]   [2] Line 5409, d:\Cloud\SourcePawn\GitHub\Surftimer-olokos\addons\sourcemod\scripting\surftimer/sql.sp::sql_selectRankedPlayersCallback
`
This happens on !ckadmin and recalculate player stats
But other than this small mishap, everything seems to run perfectly, I think once this is solved, we can merge!

**Comment by Bara** [comment]
Use ``` for code block instead of single linge ( ` )

**Comment by olokos** [comment]
Done

**Comment by olokos** [comment]
Looks good to me, will upload on my server now

**Comment by olokos** [comment]
```
say I literally am doing a backup of ts3server right now
Console: I literally am doing a backup of ts3server right now
say but var aint bad at all
Console: but var aint bad at all
appLe.: oh really
olokos: say, yea, entire ts3server db,icons and everything running atm
L 05/11/2020 - 20:16:31: [SM] Exception reported: Array index out-of-bounds (index 66, limit 66)
L 05/11/2020 - 20:16:31: [SM] Blaming: SurfTimer.smx
L 05/11/2020 - 20:16:31: [SM] Call stack trace:
L 05/11/2020 - 20:16:31: [SM]   [1] Line 607, surftimer/sql.sp::CalculatePlayerRank
L 05/11/2020 - 20:16:31: [SM]   [2] Line 5409, surftimer/sql.sp::sql_selectRankedPlayersCallback
```

**Comment by olokos** [comment]
I am executing !ckadmins while ingame with 99:z permissions, so I think this if won't do much 😅 

But yea, I merged another PR and with that the rest of dev branch.

I think once we get this PR ready for public release, we can release 286!

**Comment by LubricantJam** [comment]
@olokos Could you report back on this before merge?

**Comment by Bara** [comment]
@LubricantJam I'm back now, feel free to approve it or request changes.

**Pull request merged**
