### PR TITLE
Stripper formatting changes

### PR DESCRIPTION
**Pull request by Kyli3Boi**
Uhm what can i say... formatting was bothering me and hope this will be valuable to some. This took awhile xD

### CODE REVIEW

**Comment by Kyli3Boi** [comment]
If this is approved for merge then please either don't merge Multiple stripper updates #206 or Merge Multiple stripper updates #206 first and then this as this contains formatting changes on the files in Multiple stripper updates #206

**Comment by Kyli3Boi** [comment]
Basically all that iv done is remove multiple spaces, fix line spacing, and changed the below:

From eg.
add:
{
}

add:
{
}

add:
{
}

Changed to eg.

add:
{
}
{
}
{
}

**Comment by sneak-it** [comment]
[**@Kyli3Boi**](https://github.com/Kyli3Boi) commented on [Jul 14, 2020, 5:34 AM EDT](https://github.com/surftimer/Surftimer-olokos/pull/207#issuecomment-658079356 "2020-07-14T09:34:11Z - Replied by Github Reply Comments"):
> Basically all that iv done is remove multiple spaces, fix line spacing, and changed the below:

That's what I saw, and is definitely good practice 👍

**Comment by olokos** [comment]
Needs resolving conflicts, but almost ready to merge @Kyli3Boi

**Comment by sneak-it** [comment]
I went ahead and resolved the conflicts, thank you for your contribution!

**Comment by Kyli3Boi** [comment]
Thank you @sneak-it

**Comment by olokos** [comment]
Great job guys, thank you very much for your help! ❤️

**Pull request merged**
